CREATE DATABASE 酒店管理系统
ON PRIMARY(
NAME = '酒店管理系统_DATA',
FILENAME = 'D:\SJK\酒店管理系统_DATA.MDF',
SIZE = 2MB,
MAXSIZE = 200MB,
FILEGROWTH = 2MB
)

LOG ON(
NAME = '酒店管理系统_LOG',
FILENAME = 'D:\SJK\酒店管理系统_LOG.LDF',
SIZE = 2MB,
MAXSIZE = 200MB,
FILEGROWTH = 2MB
)
GO