//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMS.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap module {
            get {
                object obj = ResourceManager.GetObject("module", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap module_select {
            get {
                object obj = ResourceManager.GetObject("module_select", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolButton_Search.
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap ToolButton_Abolish {
            get {
                object obj = ResourceManager.GetObject("ToolButton_Abolish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ToolButton_Audit {
            get {
                object obj = ResourceManager.GetObject("ToolButton_Audit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ToolButton_Cancel {
            get {
                object obj = ResourceManager.GetObject("ToolButton_Cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ToolButton_Checkout {
            get {
                object obj = ResourceManager.GetObject("ToolButton_Checkout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ToolButton_ClearData {
            get {
                object obj = ResourceManager.GetObject("ToolButton_ClearData", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ToolButton_Computer {
            get {
                object obj = ResourceManager.GetObject("ToolButton_Computer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ToolButton_Delete {
            get {
                object obj = ResourceManager.GetObject("ToolButton_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ToolButton_Descend {
            get {
                object obj = ResourceManager.GetObject("ToolButton_Descend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ToolButton_Download {
            get {
                object obj = ResourceManager.GetObject("ToolButton_Download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ToolButton_ErrorImage {
            get {
                object obj = ResourceManager.GetObject("ToolButton_ErrorImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ToolButton_ExportExcel {
            get {
                object obj = ResourceManager.GetObject("ToolButton_ExportExcel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ToolButton_ExportTemplate {
            get {
                object obj = ResourceManager.GetObject("ToolButton_ExportTemplate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ToolButton_ExportWord {
            get {
                object obj = ResourceManager.GetObject("ToolButton_ExportWord", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ToolButton_Help {
            get {
                object obj = ResourceManager.GetObject("ToolButton_Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ToolButton_ImportData {
            get {
                object obj = ResourceManager.GetObject("ToolButton_ImportData", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ToolButton_Modify {
            get {
                object obj = ResourceManager.GetObject("ToolButton_Modify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ToolButton_New {
            get {
                object obj = ResourceManager.GetObject("ToolButton_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ToolButton_Popup {
            get {
                object obj = ResourceManager.GetObject("ToolButton_Popup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ToolButton_Print {
            get {
                object obj = ResourceManager.GetObject("ToolButton_Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ToolButton_PrintPreview {
            get {
                object obj = ResourceManager.GetObject("ToolButton_PrintPreview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ToolButton_RAudit {
            get {
                object obj = ResourceManager.GetObject("ToolButton_RAudit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ToolButton_Save {
            get {
                object obj = ResourceManager.GetObject("ToolButton_Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ToolButton_Signin {
            get {
                object obj = ResourceManager.GetObject("ToolButton_Signin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ToolButton_Start {
            get {
                object obj = ResourceManager.GetObject("ToolButton_Start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ToolButton_Stat {
            get {
                object obj = ResourceManager.GetObject("ToolButton_Stat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ToolButton_Stop {
            get {
                object obj = ResourceManager.GetObject("ToolButton_Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ToolButton_Submit {
            get {
                object obj = ResourceManager.GetObject("ToolButton_Submit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ToolButton_Update {
            get {
                object obj = ResourceManager.GetObject("ToolButton_Update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ToolButton_View {
            get {
                object obj = ResourceManager.GetObject("ToolButton_View", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
