USE 酒店管理系统
GO
CREATE PROC PROC_预订历史  @预订单号 CHAR(10)
AS
BEGIN TRAN
INSERT INTO 预订单历史 SELECT * FROM 预订单 WHERE 预订单号 = @预订单号
COMMIT
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC PROC_入住单历史   @入住单号 CHAR(10)
AS
BEGIN TRAN 
INSERT INTO 入住单历史 SELECT * FROM 入住单 WHERE 入住单号 = @入住单号
COMMIT
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC PROC_帐单明细历史  @帐单编号 CHAR(10)
AS
BEGIN TRAN
INSERT INTO 帐单明细历史 SELECT * FROM 帐单明细 WHERE 帐单编号 = @帐单编号
COMMIT
GO